import { Download, FileBarChart2 } from "lucide-react";

export function ReportsPage() {
  const mockData = [
    { id: "REP-01", name: "Monthly Sales Overview", type: "Financial", date: "Oct 1, 2026", generatedBy: "System" },
    { id: "REP-02", name: "Chef Performance Metrics", type: "Performance", date: "Sep 28, 2026", generatedBy: "Lana Admin" },
    { id: "REP-03", name: "Customer Growth & Retention", type: "Analytics", date: "Sep 15, 2026", generatedBy: "System" },
  ];

  return (
    <div className="space-y-6">
      <div className="flex justify-between items-end">
        <div>
          <h1 className="text-2xl font-bold text-text-primary tracking-tight">System Reports</h1>
          <p className="text-text-secondary mt-1">Generate and download platform analytics.</p>
        </div>
        <button className="bg-primary text-white px-4 py-2 rounded-lg text-sm font-semibold hover:bg-primary-dark transition-colors">+ Generate Report</button>
      </div>

      <div className="bg-surface border border-border rounded-2xl shadow-sm overflow-hidden overflow-x-auto">
        <table className="w-full text-start border-collapse min-w-[600px]">
          <thead>
            <tr className="bg-background text-text-secondary text-xs uppercase tracking-wider">
              <th className="px-6 py-4 font-medium">Report Name</th>
              <th className="px-6 py-4 font-medium">Type</th>
              <th className="px-6 py-4 font-medium">Generated Date</th>
              <th className="px-6 py-4 font-medium">Generated By</th>
              <th className="px-6 py-4 font-medium text-end">Actions</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-border text-sm">
            {mockData.map((row) => (
              <tr key={row.id} className="hover:bg-background/50 transition-colors">
                <td className="px-6 py-4 font-medium text-text-primary flex items-center gap-2">
                  <FileBarChart2 size={16} className="text-primary"/> {row.name}
                </td>
                <td className="px-6 py-4 text-text-secondary">{row.type}</td>
                <td className="px-6 py-4 text-text-secondary">{row.date}</td>
                <td className="px-6 py-4 text-text-secondary">{row.generatedBy}</td>
                <td className="px-6 py-4 text-end">
                  <button className="p-1.5 text-text-secondary hover:text-primary transition-colors flex items-center gap-1 ml-auto">
                    <Download size={16} /> <span className="text-xs font-medium">Download</span>
                  </button>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  );
}
